update=2015/03/20 22:22:07
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Users/kemushi/Dropbox/KiCad/lib/basic
LibName2=C:/Users/kemushi/Dropbox/KiCad/lib/CONN
LibName3=C:/Users/kemushi/Dropbox/KiCad/lib/DIODE
LibName4=C:/Users/kemushi/Dropbox/KiCad/lib/FET
LibName5=C:/Users/kemushi/Dropbox/KiCad/lib/holder
LibName6=C:/Users/kemushi/Dropbox/KiCad/lib/LDO
LibName7=C:/Users/kemushi/Dropbox/KiCad/lib/modem
LibName8=C:/Users/kemushi/Dropbox/KiCad/lib/msp430
LibName9=C:/Users/kemushi/Dropbox/KiCad/lib/PIC
LibName10=C:/Users/kemushi/Dropbox/KiCad/lib/PMIC
LibName11=C:/Users/kemushi/Dropbox/KiCad/lib/power
LibName12=C:/Users/kemushi/Dropbox/KiCad/lib/RAM
LibName13=C:/Users/kemushi/Dropbox/KiCad/lib/RF
LibName14=C:/Users/kemushi/Dropbox/KiCad/lib/ROM
LibName15=C:/Users/kemushi/Dropbox/KiCad/lib/Sensor
LibName16=C:/Users/kemushi/Dropbox/KiCad/lib/socket
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=CAL430F_PROG.net
UseCmpFile=0
PadDrill=0.6
PadDrillOvalY=0.6
PadSizeH=1.5
PadSizeV=1.5
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.09999999999999999
ModuleOutlineThickness=0.15
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
